rename dependabot file
InformedSolutions/JAQU-CAZ-Payments-API pull request #322
Opened 2020-08-07 12:06 UTC by ISJDF

2020-08-28 09:47 UTC, cruddasj requested changes

2020-08-28 09:47 UTC, cruddasj commented on .drone2.yml
> +      - python3 ./ci-cd-resources/subscribe_to_alert_topics.py -e freeable-memory -e 4xx -e usage -e evictions -e csv -i prod -i payments ISSupport-CAZ@informed.com
Can we please remove this from the commit? It's also worth noting this needs a profile supplied in keep with the example at 
https://github.com/InformedSolutions/JAQU-CAZ-Retrofit-API/blob/344aee5cd559b33649b02238539bb46d721770bf/.drone2.yml#L1524

2020-09-04 11:02 UTC, ISJDF commented on .drone2.yml
> +      - python3 ./ci-cd-resources/subscribe_to_alert_topics.py -e freeable-memory -e 4xx -e usage -e evictions -e csv -i prod -i payments ISSupport-CAZ@informed.com
Removed

2020-09-22 11:15 UTC, cruddasj approved these changes

2020-09-22 11:39 UTC, merged